<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <RootNamespace>DiscBox</RootNamespace>
    <AssemblyName>DiscBox</AssemblyName>
    <ApplicationIcon>Assets\DiscBox.ico</ApplicationIcon>
    <Version>0.1.1</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.3" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.3" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
    <PackageReference Include="Material.Icons.Avalonia" Version="2.1.0" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.2.3" Condition="'$(Configuration)' == 'Debug'" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="lib*.dll" CopyToOutputDirectory="PreserveNewest" />
    <None Include="zlib1.dll" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\UploadProgressWindow.axaml.cs">
      <DependentUpon>UploadProgressWindow.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\NewFolderDialog.axaml.cs">
      <DependentUpon>NewFolderDialog.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\ConfirmDeleteDialog.axaml.cs">
      <DependentUpon>ConfirmDeleteDialog.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\TransferProgressWindow.axaml.cs">
      <DependentUpon>TransferProgressWindow.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\CloudSyncProgressWindow.axaml.cs">
      <DependentUpon>CloudSyncProgressWindow.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\ConfirmDriveRemoveDialog.axaml.cs">
      <DependentUpon>ConfirmDriveRemoveDialog.axaml</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
